#!/bin/bash
set -e

LAUNCH_AGENT_PLIST="$HOME/Library/LaunchAgents/com.stripe.u2f-touchid.plist"

# Write a LaunchAgent plist so app starts at login
cat > $LAUNCH_AGENT_PLIST << EOT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>com.stripe.u2f-touchid</string>
		<key>Program</key>
		<string>/Applications/U2FTouchID.app/Contents/MacOS/U2FTouchID</string>
		<key>ProgramArguments</key>
		<array>
			<string>/Applications/U2FTouchID.app/Contents/MacOS/U2FTouchID</string>
		</array>
		<key>RunAtLoad</key>
		<true/>
		<key>KeepAlive</key>
		<true/>
	</dict>
</plist>
EOT

# Make sure the plist is owned by the user (otherwise it runs as root)
chown ${USER}:staff $LAUNCH_AGENT_PLIST

# Launch the app
sudo -u${USER} launchctl load $LAUNCH_AGENT_PLIST

exit 0
